// Global balance/config knobs for fast gameplay tuning.
const BALANCE={
 waves:{
  breakDuration:6,
  baseEnemyCount:12,
  perWaveEnemyCount:5,
  spawnIntervalBase:1.4,
  spawnIntervalWaveScale:0.12,
  spawnIntervalMin:0.12,
  spawnBatchBase:1,
  spawnBatchWaveScale:0.5,
  spawnBatchMax:6,
  maxAliveBase:50,
  maxAlivePerWave:5
 },
 objectives:{
  spawnInterval:22,
  minWave:2,
  penaltyDuration:12,
  penaltyEnemySpeedMult:1.15,
  hold:{
   radius:115,
   targetTime:12,
   decayPerSec:1.4,
   rewardCoins:20,
   rewardShield:2.5
  },
  hazard:{
   radius:26,
   hp:520,
   duration:22,
   pulseEvery:1.4,
   pulseRadius:150,
   pulseDamage:8,
   rewardCoins:30,
   rewardXp:45
  },
  escort:{
   machineRadius:36,
   orbRadius:11,
   orbFollowSpeed:210,
   targetApproachSpeed:170,
   tetherDistance:250,
   rewardCoins:25,
   rewardEmpRadius:220,
   rewardEmpDamage:90
  }
 },
 drops:{
  enemyXpMultiplier:1,
  enemyCoinChance:0.3,
  enemyCoinValueMultiplier:1,
  enemyHpDropChance:0.03,
  goldrushCoinHitChance:0.25,
  expenseBonusCoinDrops:2,
  bossCoinBurstCount:10,
  bossCoinValueDivisor:10
 },
 magnet:{
  baseRange:45,
  minRange:10,
  levelUpBonus:25,
  pullMinSpeed:380,
  pullBaseSpeed:760,
  pullDistanceFactor:4.2
 },
 arena:{
  hazards:{
   maxActive:3,
   spawnInterval:20,
   spawnMinDist:220,
   spawnMaxDist:800,
   zapZone:{
    radius:90,
    life:18,
    interval:1.2,
    warning:0.8,
    activeDuration:0.5,
    cooldown:1.2,
    enemyDamage:32,
    playerDamage:16,
    enemySlow:0.6
   }
  },
  tools:{
   maxActive:4,
   spawnInterval:25,
   spawnMinDist:180,
   spawnMaxDist:420,
   barrelChance:0.6,
   barrel:{
    radius:16,
    hp:35,
    explosionRadius:110,
    chainRadius:140,
    enemyDamage:70,
    playerDamage:25,
    knockback:45
   },
   coffee:{
    radius:22,
    cooldown:20,
    healPercent:0.12,
    enemySpawnOnUse:2
   }
  }
 }
};
