// Global balance/config knobs for fast gameplay tuning.
const BALANCE={
 director:{
  spawnPopDuration:0.35,
  spawnPopMinScale:0.12,
  waveDuration:50,
  scaling:{
   ambientRate:1,
   eventFrequency:1,
   eventSize:1,
   eventSpeed:1,
   eventRadius:1,
   budgetMultiplier:1,
   budgetPost10Growth:1.12,
   enemyStatGrowth:1.2,
   bossStatGrowth:3,
   roleTierShift:0
  },
  ambient:{
   intervalWave1:2,
   intervalWave10:.3
  },
  events:{
   types:['CIRCLE','STAMPEDE','AMBUSH'],
   stampede:{
    rushDuration:2.8
   },
   ambush:{
    distance:250
   }
  },
  budget:{
   wave1:10,
   wave10:1000,
   cost:{weak:1,fast:2,tank:10}
  },
  mix:{
   weakWave1:1,
   weakWave10:.6,
   fastWave1:0,
   fastWave10:.3
  },
  specialEnemies:{
   micromanagerRate:0.06,
   sniperRate:0.04,
   maxMicromanagerAlive:2,
   maxSniperAlive:2,
   micromanager:{
    budgetRole:'fast',
    buffRadius:100,
    hp:300
   },
   sniper:{
    budgetRole:'fast',
    chargeTime:2,
    cooldown:4,
    projectileSpeed:560,
    minRange:260,
    maxRange:520,
    laserDuration:0.8,
    laserWidth:12,
    laserTick:0.25,
    laserDamage:18
  }
   },
   bossHazards:{
  zap:{
   radius:120,
   interval:6,
   warning:0.8,
   activeDuration:0.6,
   cooldown:0.8,
   playerDamage:14
  },
  laser:{
   radius:260,
   width:10,
   interval:9,
   warning:0.7,
   duration:3.4,
   rotateSpeed:1.8,
   tickDamage:16
  }
 }
 },
 waves:{
  breakDuration:3,
  baseEnemyCount:12,
  perWaveEnemyCount:5,
  spawnIntervalBase:1.4,
  spawnIntervalWaveScale:0.12,
  spawnIntervalMin:0.12,
  spawnBatchBase:1,
  expenseDuration:5,
  spawnBatchWaveScale:0.5,
  spawnBatchMax:6,
  maxAliveBase:50,
  maxAlivePerWave:5
 },
 objectives:{
  spawnInterval:22,
  minWave:2,
  penaltyDuration:12,
  penaltyEnemySpeedMult:1.15,
  hold:{
   radius:115,
   targetTime:12,
   timeout:22,
   decayPerSec:1.4,
   rewardCoins:20,
   rewardShield:2.5
  },
  hazard:{
   radius:26,
   hp:520,
   duration:22,
   timeout:22,
   pulseEvery:1.4,
   pulseRadius:150,
   pulseDamage:8,
   rewardCoins:15,
   rewardXp:45
  },
  escort:{
   durationBase:6,
   durationPer100px:1.1,
   durationMin:10,
   durationMax:40,
   machineRadius:36,
   orbRadius:11,
   orbFollowSpeed:210,
   targetApproachSpeed:170,
   tetherDistance:250,
   rewardCoins:10,
   rewardEmpRadius:220,
   rewardEmpDamage:90
    },
    coffee:{
     count:4,
     radius:16,
     timeout:20,
     spawnMinDist:140,
     spawnMaxDist:520,
     rewardCoins:15,
     rewardXp:30
   },
   call:{
    radius:120,
    targetTime:10,
    timeout:22,
    decayPerSec:1.6,
    rewardCoins:18,
    rewardXp:35
  }
 },
 drops:{
  xpPickupLifetime:15,
  coinPickupLifetime:15,
  enemyXpMultiplier:1,
  enemyCoinChance:0.01,
  enemyCoinValueMultiplier:1,
  enemyHpDropChance:0.03,
  goldrushCoinHitChance:0.1,
  expenseBonusCoinDrops:2,
  bossCoinBurstCount:10,
  bossCoinValueDivisor:10
 },
 magnet:{
  baseRange:45,
  minRange:10,
  levelUpBonus:25,
  pullMinSpeed:380,
  pullBaseSpeed:760,
  pullDistanceFactor:4.2
 },
 arena:{
  hazards:{
   maxActive:3,
   spawnInterval:20,
   spawnMinDist:220,
   spawnMaxDist:800,
   zapZone:{
    radius:90,
    life:18,
    interval:1.2,
    warning:0.8,
    activeDuration:0.5,
    cooldown:1.2,
    enemyDamage:32,
    playerDamage:16,
    enemySlow:0.6
   }
  },
  tools:{
   maxActive:4,
   spawnInterval:25,
   spawnMinDist:180,
   spawnMaxDist:420,
   barrelChance:0.6,
   barrel:{
    radius:16,
    hp:35,
    explosionRadius:110,
    chainRadius:140,
    enemyDamage:70,
    playerDamage:25,
    knockback:45
   },
   coffee:{
    radius:22,
    cooldown:20,
    healPercent:0.12,
    enemySpawnOnUse:2
   }
  }
 },
 environment:{
  photocopier:{
   spawnInterval:18,
   maxActive:3,
   spawnMinDist:220,
   spawnMaxDist:700,
   fuse:3,
   radius:300,
   enemyDamage:95,
   playerDamage:18
  }
 }
};
