// Global balance/config knobs for fast gameplay tuning.
const BALANCE={
 waves:{
  breakDuration:6,
  baseEnemyCount:12,
  perWaveEnemyCount:5,
  spawnIntervalBase:1.4,
  spawnIntervalWaveScale:0.12,
  spawnIntervalMin:0.12,
  spawnBatchBase:1,
  spawnBatchWaveScale:0.5,
  spawnBatchMax:6,
  maxAliveBase:50,
  maxAlivePerWave:5
 },
 magnet:{
  baseRange:45,
  minRange:10,
  levelUpBonus:25,
  pullMinSpeed:380,
  pullBaseSpeed:760,
  pullDistanceFactor:4.2
 },
 arena:{
  hazards:{
   maxActive:3,
   spawnInterval:20,
   spawnMinDist:220,
   spawnMaxDist:800,
   zapZone:{
    radius:90,
    life:18,
    interval:1.2,
    warning:0.8,
    activeDuration:0.5,
    cooldown:1.2,
    enemyDamage:32,
    playerDamage:8,
    enemySlow:0.6
   }
  },
  tools:{
   maxActive:4,
   spawnInterval:25,
   spawnMinDist:180,
   spawnMaxDist:420,
   barrelChance:0.6,
   barrel:{
    radius:16,
    hp:35,
    explosionRadius:110,
    chainRadius:140,
    enemyDamage:70,
    playerDamage:25,
    knockback:45
   },
   coffee:{
    radius:22,
    cooldown:20,
    healPercent:0.12,
    enemySpawnOnUse:2
   }
  }
 }
};
